#!/bin/sh

postgres_ready(){
    python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${DB_HOST}",
        port=5432,
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
#until 참이 될때까지 반복
until postgres_ready; do
    >&2 echo "Wating for PostgreSQL..."
    sleep 1
done
#모든 출력 결과물을 표준 에러에다 넣는다.
>&2 echo "PostgreSQL is available"

exec "$@" #뒤에오는 커멘드 실행